#!/usr/bin/env bash
# Load Balancer-01 login commands

# Setting up the SSH-agent
eval $("ssh-agent")

# Path to IdentityFile
ssh-add ~/.ssh/school

# Username and IP Address 
ssh ubuntu@54.197.127.220

