#!/usr/bin/env bash
# backsup and compresses my databases

# Declaration of variables
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"


mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "$file_name" backup.sql

