#!/usr/bin/env bash
# This Script displays "To infinity and beyond" indefinitely with
#+ a sleep 2 in between each iteration,
#   displaying " I am invincible!!!" in between each iteration

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
