#!/usr/bin/env bash
# This Script displays the contents of the current directory in list format
#   displaying only the part of the name after the first dash 

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done

