#!/usr/bin/env bash
# nginx is run as nginx user and listening on all active IPs on port 8080.
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
pkill apache2
# restart
su nginx -s /bin/bash -c 'service nginx restart'

