#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080
chmod 644 /etc/nginx/nginx.conf
sed -i 's/^\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/\s*listen .*/listen 8080;/' /etc/nginx/sites-enabled/default
pkill apache2
sed -i 's/^pid .*/pid \/run\/nginx.pid;/' /etc/nginx/nginx.conf
su nginx -s /bin/bash -c 'nginx'

