#!/usr/bin/env bash
#SSH client configuration
Host *
  PasswordAuthentication no
  IdentifityFile ~/.ssh/school
  SendEnv LANG lc_*
  HashKnownHOsts yes
  GSSAPIAuthentication yes
  GSSAAPIDelegateCredentials no

